Telegram feature
HSE-Courseworks/MLOps_pipeline pull request #1
Opened 2023-10-07 17:54 UTC by ArtemOvsyannikov

Create a Telegram object based on task's description in flashcard

2023-10-08 12:22 UTC, DumDereDum requested changes

2023-10-08 12:22 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +
Вот сюда нужно добавить 

if __name__ == "__main__":

Чтобы код ниже запускался только тогда, когда ты запускаешь именно этот файл

2023-10-08 12:22 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +                print(f"Post text: {message.text}\nViews: {message.views}")
У тебя злеть происходит печать, а нам это не подходит, тебе нужно создать pandas.DataFrame и возвращать его, либо возвращать словарь

2023-10-08 12:22 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +                        print(f"Reaction: {reaction.emoji}\ncount: {reaction.count}\n")
Помимо текстов, реакций и просмотров, добавь сохранение остальных метаданных, таких как время публикации, картинку приложенную и так далее, пока забираем все что можно из тг, убрать лишнюю инфу можно, а вот добавить новую затруднительно

2023-10-08 12:22 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +posts = client.get_n_last_posts(chat_id, n)
posts будет None, если я не ошибаюсь, потому что в функции у тебя нет return'a

2023-10-08 17:25 UTC, ArtemOvsyannikov commented
Насчет медиафайлов: вытаскивал только айдишники прикрепленных файлов, рекламные посты обрабатываются, но их медиафайлы - нет, ибо обычно у них там ссылка на вебпейджы и т.д. 
Не знаю, в каком формате лучше обрабатывать прикрепленные файлы, поэтому буду ждать советов, какую инфу по медиа лучше вытаскивать

2023-10-08 17:35 UTC, DumDereDum requested changes

2023-10-08 17:35 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +                    data[i]['Media'] = None
Как оно будет работать если у нас в после есть и картинка и видео, в новостных каналах так часто встречается

2023-10-08 17:51 UTC, ArtemOvsyannikov commented
Есть такой нюанс: каждое прикрепленное медиа в пирограме выносится в отдельный пост, пока хз, как с таким работать, буду думать, но есть идея, чтобы запускать в таком случае какой-то мини-цикл, который будет эти "обрвыки" в один нормальный пост укомплектовывать.

2023-10-09 15:30 UTC, sh1ronchik commented
Пока так, теперь все медиа файлы в рамках одного поста считываются адекватно и пихаются в один "пост". Сразу скажу, обработка иных типов прикрепленных файлов, кроме фото и видео я не делал. Если сообщество что-то закрепляет, то это тоже отображается, как пост. Обработку этого пока не прикручивал.

2023-10-15 10:06 UTC, DumDereDum requested changes

2023-10-15 10:06 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +                if message.date != post_date:
заменить на id "media_group_id"

2023-10-15 10:07 UTC, DumDereDum requested changes

2023-10-15 10:07 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +    def get_n_last_posts(self, chat_id, n):
нужно прописать логику где n берется с запасом, так как тут ты считываешь кол-во вложений а нам нужно кол-во постов

2023-10-15 10:07 UTC, DumDereDum commented on telegram-feature/telegram_utils.py
> +    def get_n_last_posts(self, chat_id, n):
бери с запасо 10, потому что это максимальное возвомжное кол-во вложений в файл

2023-10-21 08:30 UTC, DumDereDum approved these changes
👍 +1

2023-10-21 08:31 UTC, merged