Add test DAG
HSE-Courseworks/MLOps_pipeline pull request #2
Opened 2023-10-14 17:33 UTC by Sherukas

2023-10-14 17:52 UTC, ArtemOvsyannikov commented
Крутой!

2023-10-15 09:44 UTC, DumDereDum commented
* добавить gitignore и в него файлы, которые генерятся автоматически, по типо airflow.cfg или __pycache__/
* написать докер файлы и docker-compose самостоятельно
* не успользовать уже готовый код в котором просто коментируются строчки
* назвать папку ariflow и в ней оставить папку dags/ и вайл Dockerfile
* docker-compose положить в корень проекта (в нем сделать запуск только airflow и postgress)

2023-10-28 12:40 UTC, DumDereDum requested changes

2023-10-28 12:40 UTC, DumDereDum commented on .gitignore
> +telegram-feature/help.txt
добавить сюда папку от постгреса `postgres-db-volume`

2023-11-04 07:08 UTC, DumDereDum approved these changes
👍

2023-11-04 07:08 UTC, merged